### PR TITLE
Escape filename in glob in ConfigMixIn (#2136)

### PR DESCRIPTION
**Pull request by alexharv074**
Call glob.escape on filename to handle any unsafe characters prior to
globbing.

### CODE REVIEW

**Comment by kddejong** [comment]
I cannot replicate the issue locally.  Trying to figure out why this is failing.

**Comment by alexharv074** [comment]
@kddejong Are you saying you weren't able to reproduce this even with the details I gave in the issue here? https://github.com/aws-cloudformation/cfn-lint/issues/2136

**Comment by kddejong** [comment]
Here is the issue from what I can tell `test/fixtures/templates/public/*.yaml` is becoming `test/fixtures/templates/public/[*].yaml` which is resulting in the `*` not being expanded.

**Comment by kddejong** [comment]
Going to close this one.  We can re-open as needed.

**Pull request closed without merging**
