### PR TITLE
Passthrough metadata into SAM translator

### LINKED ISSUE #3028: Use samtranslate `passthrough_metadata` to support ignoring checks on Serverless resources
### Is this feature request related to a new rule or cfn-lint capabilities?

_No response_

### Describe the feature you'd like to request

Based on this: https://github.com/aws/serverless-application-model/pull/2224, it looks like it should be possible to ask SAM to bring all the Metadata stored on the original AWS::Serverless::* resources through to the translated resources. Doing that should allow cfn-lint to check the Metadata section for resource level ignores.

I actually tried changing the parameter myself but couldn't get it working. I must be missing something....

### Describe the solution you'd like

Enable `passthrough_metadata` on the samtranslate `translate` call to bring ALL the metadata through and properly support resource level ignores on serverless resources.

### Additional context

This is where I tried to add the parameter: https://github.com/aws-cloudformation/cfn-lint/blob/main/src/cfnlint/template/transforms/_sam.py#L155

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by kddejong**
*Issue #, if available:*
fix #3028 

*Description of changes:*
- Add `passthrough_metadata=True` to SAM transform

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kddejong** [comment]
The following configuration is passed through and the error will be ignored
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300

  ApiFunction: # Adds a GET api endpoint at "/" to the ApiGatewayApi via an Api event
    Type: AWS::Serverless::Function
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E2531
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: python2.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}
```

**Comment by kddejong** [comment]
Transforms into:
```json
{
 "AWSTemplateFormatVersion": "2010-09-09",
 "Description": "AWS SAM template with a simple API definition",
 "Resources": {
  "ApiFunction": {
   "Metadata": {
    "cfn-lint": {
     "config": {
      "ignore_checks": [
       "E2531"
      ]
     }
    }
   },
   "Properties": {
    "Code": {
     "ZipFile": "def handler(event, context):\n    return {'body': 'Hello World!', 'statusCode': 200}\n"
    },
    "Handler": "index.handler",
    "Role": {
     "Fn::GetAtt": [
      "ApiFunctionRole",
      "Arn"
     ]
    },
    "Runtime": "python2.7",
    "Tags": [
     {
      "Key": "lambda:createdBy",
      "Value": "SAM"
     }
    ]
   },
   "Type": "AWS::Lambda::Function"
  },
  "ApiFunctionApiEventPermissionprod": {
   "Metadata": {
    "cfn-lint": {
     "config": {
      "ignore_checks": [
       "E2531"
      ]
     }
    }
   },
   "Properties": {
    "Action": "lambda:InvokeFunction",
    "FunctionName": {
     "Ref": "ApiFunction"
    },
    "Principal": "apigateway.amazonaws.com",
    "SourceArn": {
     "Fn::Sub": [
      "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/",
      {
       "__ApiId__": {
        "Ref": "ApiGatewayApi"
       },
       "__Stage__": "*"
      }
     ]
    }
   },
   "Type": "AWS::Lambda::Permission"
  },
  "ApiFunctionRole": {
   "Metadata": {
    "cfn-lint": {
     "config": {
      "ignore_checks": [
       "E2531"
      ]
     }
    }
   },
   "Properties": {
    "AssumeRolePolicyDocument": {
     "Statement": [
      {
       "Action": [
        "sts:AssumeRole"
       ],
       "Effect": "Allow",
       "Principal": {
        "Service": [
         "lambda.amazonaws.com"
        ]
       }
      }
     ],
     "Version": "2012-10-17"
    },
    "ManagedPolicyArns": [
     "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    ],
    "Tags": [
     {
      "Key": "lambda:createdBy",
      "Value": "SAM"
     }
    ]
   },
   "Type": "AWS::IAM::Role"
  },
  "ApiGatewayApi": {
   "Properties": {
    "BodyS3Location": {
     "Bucket": "bucket",
     "Key": "value"
    }
   },
   "Type": "AWS::ApiGateway::RestApi"
  },
  "ApiGatewayApiDeployment6ab35d56ae": {
   "Properties": {
    "Description": "RestApi deployment id: 6ab35d56aec65900e2dcd7425c04f84894e835c5",
    "RestApiId": {
     "Ref": "ApiGatewayApi"
    },
    "StageName": "Stage"
   },
   "Type": "AWS::ApiGateway::Deployment"
  },
  "ApiGatewayApiprodStage": {
   "Properties": {
    "CacheClusterEnabled": true,
    "CacheClusterSize": "0.5",
    "DeploymentId": {
     "Ref": "ApiGatewayApiDeployment6ab35d56ae"
    },
    "MethodSettings": [
     {
      "CacheTtlInSeconds": 300,
      "CachingEnabled": true,
      "HttpMethod": "GET",
      "ResourcePath": "/"
     }
    ],
    "RestApiId": {
     "Ref": "ApiGatewayApi"
    },
    "StageName": "prod"
   },
   "Type": "AWS::ApiGateway::Stage"
  }
 }
}
```

**Comment by mew1033** [comment]
I'm still having issues with this: https://github.com/aws-cloudformation/cfn-lint/issues/3028#issuecomment-1906872626

**Comment by mew1033** [comment]
It's working now. Sweet!

**Pull request merged**
