### PR TITLE
feat: stringMax validation for Lambda, IAM and SNS

### PR DESCRIPTION
**Pull request by luchees**
*Issue #, if available:*
#2080

*Description of changes:*
Implemented stringMax for several properties of Lambda, IAM and SNS. This will validate the properties against their max length supported by AWS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by luchees** [comment]
I was able to update the CloudSpecs but now I'm not able to update them after I was trying to fix the error I get in the tests.
Could someone help me further? thank you.

I did try 
pip install -e .
cfn-lint -u

**Comment by kddejong** [comment]
I can take a look

**Comment by kddejong** [comment]
I took your work and added it. Can you look at the new PR.

**Comment by kddejong** [comment]
Your commits were integrated into the other PR.

**Pull request closed without merging**
