### PR TITLE
feature (schema) - Support resource schemas as a methodology to validate resource configuration

### PR DESCRIPTION
**Pull request by kddejong**
*Issue #, if available:*

*Description of changes:*
- Convert to using the [resource provider schema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html) when providing the `--include-experimental` flag

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kddejong** [comment]
Lots of changes in the final change.  Look at https://github.com/aws-cloudformation/cfn-lint/pull/2325/commits/6b60b6aa675c4b525883d668851fd3f4eed377f5 for all the changes that aren't associated to downloading the resource type specs

**Comment by PatMyron** [comment]
Haven't read the code, but high-level thoughts:

1) Make sense to have rollout steps? (new version behind flag, default to new version and old version available with flag, then remove old version)

2) % resource types migrated to registry to switch primary method from specs to schemas? Registry's currently 664/997 resource types

3) re-hash of https://github.com/aws-cloudformation/cfn-lint/issues/2455 discussion where these unzipped schemas are as large as the specifications, should we even unzip them before checking them in? Seems unreviewable either way now when there are tens of thousands of schema files

```sh
# large region: us-east-1
6.6M	CloudformationSchema/
1.1M	CloudformationSchema.zip
# small region: eu-south-1
3.8M	CloudformationSchema/
616K	CloudformationSchema.zip
```

**Comment by kddejong** [comment]
@PatMyron 


> Haven't read the code, but high-level thoughts:
> 
>     1. Make sense to have rollout steps? (new version behind flag, default to new version and old version available with flag, then remove old version)

I'm debating doing a beta version under the v1.x.x. namespace to start.  This one has been hard to hide under a feature flag because we have been so dependent on the structure of the specs.

> 
>     2. % resource types migrated to registry to switch primary method from specs to schemas? Registry's currently 664/997 resource types
> 
>     3. re-hash of [Decrease installation size #2455](https://github.com/aws-cloudformation/cfn-lint/issues/2455) discussion where these unzipped schemas are as large as the specifications, should we even unzip them before checking them in? Seems unreviewable either way now when there are tens of thousands of schema files
>
Open to ideas here.  The way it is now is that files are soft linked if they are duplicate to the files in us-east-1.  I believe this installation size was actually smaller but I would have to double check that.

> 
> ```shell
> # large region: us-east-1
> 6.6M	CloudformationSchema/
> 1.1M	CloudformationSchema.zip
> # small region: eu-south-1
> 3.8M	CloudformationSchema/
> 616K	CloudformationSchema.zip
> ```

**Comment by kddejong** [comment]
Replacing this PR with #2583

**Pull request closed without merging**
