### PR TITLE
fix: add node 22 lts, #fixes 3837

### PR DESCRIPTION
**Pull request by JamesKyburz**
*Issue #3837*

*Description of changes:*

Add Node 22 validation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by BigButovskyi** [comment]
thats is really good work, thx @JamesKyburz 👍

**Comment by r-heimann** [comment]
Aren't schemas updates pulled through the bot? https://github.com/aws-cloudformation/cfn-lint/pull/3832

Might be the case that @kddejong is busy with reinvent stuff and wasn't able to release an updated cfn-lint yet. You should be able to use `cfn-lint --update-specs` to update the cfn-lint schemas and it _should_ find the new nodejs lambda support.

**Comment by JamesKyburz** [comment]
@r-heimann It only worked for we with the changes in this pr, running `cfn-lint --update-specs` did pull down the latest schema changes but still didn't validate against Node 22.

**Comment by kddejong** [comment]
It can be hard to understand if the value came from boto, the schema, AWS APIs, pricing data, or manually.  May have to work on adding a field to the schema so its easier to understand this.

**Pull request merged**
